# Generated by Django 3.0.6 on 2020-06-28 02:59
# flake8: noqa
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0013_remove_clockedschedule_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleTimeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=None)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to Run the Multiple Time Schedule on.  Default is UTC.', verbose_name='Multiple Time Timezone')),
            ],
            options={
                'verbose_name': 'multiple_time',
                'verbose_name_plural': 'multiple_time',
                'ordering': ['timezone'],
            },
        ),
        migrations.AddField(
            model_name='periodictask',
            name='multipletime',
            field=models.ForeignKey(blank=True, help_text='Multipletime Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.MultipleTimeSchedule', verbose_name='Multipletime Schedule'),
        ),
    ]
